swagger: '2.0'

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: 1.0.0
  title: replacer-reactor
  contact:
    email: ars.anosov@gmail.com
  description: |
    Меняет DOM-элементы сайта. Использует движок [cheerio](https://github.com/cheeriojs/cheerio).

################################################################################
#                  Host, Base Path, Schemes and Content Types                  #
################################################################################
host: '192.168.13.97:8008'
basePath: /v2api
schemes:
  - http

################################################################################
#                                   Tags                                       #
################################################################################
tags:
  - name: Client
    description: Авторизация клиента
  - name: Http
    description: работа с index.html
  - name: Img
    description: работа с картинками (assets/images)
  - name: Script
    description: работа со скриптами (assets/scripts)
################################################################################
#                                    Paths                                     #
################################################################################
paths:

  /client/token:
    get:
      tags:
      - Client
      description: Получаем token
      operationId: token_get
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: auth_name
        in: query
        required: true
        type: string
        description: Имя пользователя
      - name: auth_pass
        in: query
        required: true
        type: string
        description: Пароль
      responses:
        200:
          description: token
          schema:
            $ref: '#/definitions/token_get'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
      x-swagger-router-controller: Client
    x-swagger-router-controller: Client

  /http/feed:
    get:
      tags:
        - Http
      summary: Получить элементы live-feed
      description: |
        Работает с "Живой лентой":
        1) Стягивает с сайта index.html, парсит DOM
        2) Отдает массив элементов которые отвечают за "Живую ленту"
      operationId: feed_get
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: token
          in: header
          required: true
          type: string
          description: token
        - name: idx
          in: query
          required: false
          type: integer
          description: Порядковый номер новости (с единицы)
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/feed_get'
        '202':
          description: no list
          schema:
            $ref: '#/definitions/dummy'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
      x-swagger-router-controller: Http
    post:
      tags:
        - Http
      summary: Добавить элемент live-feed
      description: Добавляет новость в "Живую ленту" 
      operationId: feed_post
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: token
          in: header
          required: true
          type: string
          description: token
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/feed_add'
          description: |
            Объект с полями, которые соответствуют DOM-элементам
      responses:
        '200':
          description: feed created
          schema:
            $ref: '#/definitions/dummy'
        '202':
          description: feed not created
          schema:
            $ref: '#/definitions/dummy'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
      x-swagger-router-controller: Http
    put:
      tags:
        - Http
      summary: Обновить элемент live-feed
      description: Обновляет новость в "Живой ленте"
      operationId: feed_put
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: token
          in: header
          required: true
          type: string
          description: token
        - name: idx
          in: query
          required: true
          type: integer
          description: Порядковый номер новости (с единицы)
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/feed_add'
          description: feed name
      responses:
        '200':
          description: feed updated
          schema:
            $ref: '#/definitions/dummy'
        '202':
          description: feed not updated
          schema:
            $ref: '#/definitions/dummy'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
      x-swagger-router-controller: Http
    delete:
      tags:
        - Http
      summary: Удалить элемент live-feed
      description: Обновляет новость в "Живой ленте"
      operationId: feed_del
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: token
          in: header
          description: token
          required: true
          type: string
        - name: idx
          in: query
          required: true
          type: integer
          description: Порядковый номер новости (с единицы)
      responses:
        '200':
          description: feed deleted
          schema:
            $ref: '#/definitions/dummy'
        '202':
          description: feed not deleted
          schema:
            $ref: '#/definitions/dummy'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
      x-swagger-router-controller: Http
    x-swagger-router-controller: Http

  /http/price:
    get:
      tags:
        - Http
      summary: Получить цену на устройство
      description: |
        1) Стягивает с сайта index.html, парсит DOM
        2) Отдает цены
      operationId: http_price_get
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: token
          in: header
          required: true
          type: string
          description: token
        - name: device
          in: query
          required: true
          type: string
          description: условное название устройства
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/http_price_get'
        '202':
          description: no device
          schema:
            $ref: '#/definitions/dummy'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
      x-swagger-router-controller: Http
    put:
      tags:
        - Http
      summary: Обновить элемент live-feed
      description: Обновляет новость в "Живой ленте"
      operationId: http_price_put
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: token
          in: header
          required: true
          type: string
          description: token
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/http_price_get'
      responses:
        '200':
          description: price updated
          schema:
            $ref: '#/definitions/dummy'
        '202':
          description: price not updated
          schema:
            $ref: '#/definitions/dummy'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
      x-swagger-router-controller: Http
    x-swagger-router-controller: Http

  /img:
    get:
      tags:
        - Img
      summary: Получить список доступных картинок
      description: |
        Выдает имена файлов картинок
      operationId: img_get
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: token
          in: header
          required: true
          type: string
          description: token
        - name: filename
          in: query
          required: false
          type: string
          description: имя файла
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/img_get'
        '202':
          description: no list
          schema:
            $ref: '#/definitions/dummy'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
      x-swagger-router-controller: Img
    post:
      tags:
        - Img
      summary: Залить картинку
      description: |
        Заливает картинку на сайт 
      operationId: img_post
      produces:
        - application/json
      consumes:
        - multipart/form-data
      parameters:
        - name: token
          in: header
          required: true
          type: string
          description: token
        - name: file
          in: formData
          required: true
          type: file
          description: картинка
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/dummy'
        '202':
          description: Image not uploaded
          schema:
            $ref: '#/definitions/dummy'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
      x-swagger-router-controller: Img
    x-swagger-router-controller: Img

  /script/addr:
    get:
      tags:
        - Script
      summary: Получить список Населенных пунктов
      description: |
        Выдает города и улицы
      operationId: script_addr_get
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: token
          in: header
          required: true
          type: string
          description: token
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/script_addr_get'
        '202':
          description: no list
          schema:
            $ref: '#/definitions/dummy'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
      x-swagger-router-controller: Script
    post:
      tags:
        - Script
      summary: Добавить Населенный пункт
      description: |
        Заливает картинку на сайт 
      operationId: script_addr_post
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: token
          in: header
          required: true
          type: string
          description: token
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/script_addr_add'
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/dummy'
        '202':
          description: Addresses not uploaded
          schema:
            $ref: '#/definitions/dummy'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
      x-swagger-router-controller: Script
    put:
      tags:
        - Script
      summary: Изменить Населенный пункт
      description: |
        Заливает картинку на сайт 
      operationId: script_addr_put
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: token
          in: header
          required: true
          type: string
          description: token
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/script_addr_add'
      responses:
        '200':
          description: Ok
          schema:
            $ref: '#/definitions/dummy'
        '202':
          description: Addresses not uploaded
          schema:
            $ref: '#/definitions/dummy'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
      x-swagger-router-controller: Script
    delete:
      tags:
        - Script
      summary: Удалить Населенный пункт
      description: Удаляет Населенный пункт
      operationId: script_addr_del
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: token
          in: header
          description: token
          required: true
          type: string
        - name: city
          in: query
          required: true
          type: string
          description: Название Населенного пункта
      responses:
        '200':
          description: address deleted
          schema:
            $ref: '#/definitions/dummy'
        '202':
          description: address not deleted
          schema:
            $ref: '#/definitions/dummy'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
      x-swagger-router-controller: Script
    x-swagger-router-controller: Script

################################################################################
#                                 Definitions                                  #
################################################################################
definitions:
# token_get =======================================================================
  token_get:
    type: "object"
    properties:
      token:
        type: "string"

# feed_get =======================================================================
  feed_get:
    type: array
    items:
      type: object
      properties:
        short_title:
          type: string
        short_img:
          type: string
        short_comments:
          type: string
        long_title:
          type: string
        long_date:
          type: string
        long_img:
          type: string
        long_content:
          type: string
        checkbox:
          type: boolean

  feed_add:
    type: object
    properties:
      short_title:
        type: string
      short_img:
        type: string
      short_comments:
        type: string
      long_title:
        type: string
      long_date:
        type: string
      long_img:
        type: string
      long_content:
        type: string
      checkbox:
          type: boolean

# img_get =======================================================================
  img_get:
    type: array
    items:
      type: string

# script_addr_get ===============================================================
  script_addr_get:
    type: array
    items:
      type: object
      properties:
        city:
          type: string
        street_arr:
          type: array
          items:
            type: string

  script_addr_add:
    type: object
    properties:
      city:
        type: string
      street_arr:
        type: array
        items:
          type: string

# http_price_get ===============================================================
  http_price_get:
    type: object
    properties:
      device:
        type: string
      price:
        type: integer

# System =======================================================================
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string

  dummy:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string